{
 "title": "fineAnts",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "traceId",
    "label": "traceId",
    "query": {}
   },
   { "name": "dashboard_uid", "query": "be9ucdsr5e1hcf" },
   { "name": "dashboard_slug", "query": "fineants" }
  ]
 },
 "panels": [
  {
   "title": "API별 예외발생 빈도",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(Path) (count_over_time({job=\"logs\", log_level=~\"warn|error\"} | logfmt | Path != `` [$__auto])))"
    }
   ]
  },
  {
   "title": "Warning Trace ID",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"logs\", log_level=\"warn\"} | traceId != `` | line_format `{{.traceId}}`"
    }
   ]
  },
  {
   "title": "Error Trace ID",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"logs\", log_level=\"error\"} | traceId != \"\" | line_format `{{.traceId}}`"
    }
   ]
  },
  {
   "title": "API별 평균 실행 시간",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg_over_time({job=\"logs\"} \n| regexp \"Path=(?P<Path>\\\\S+) ExecutionTime=(?P<TempExecutionTime>\\\\d+)ms\" \n| Path != ``\n| TempExecutionTime != `` \n| unwrap TempExecutionTime [$__auto]) \nby (Path)"
    }
   ]
  },
  {
   "title": "HTTP Log 자세히 보기",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{traceId=\"$traceId\"}"
    }
   ]
  },
  {
   "title": "HTTP Method 분포도",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(HTTPMethod) (count_over_time({job=\"logs\"} | HTTPMethod != `` [$__auto]))"
    }
   ]
  },
  {
   "title": "상위 API 10개",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(Path) (count_over_time({job=\"logs\"} | Path != `` | HTTPMethod != `` [$__auto])))"
    }
   ]
  },
  {
   "title": "IP 분포도 (상위 10개)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by(IP) (count_over_time({job=\"logs\"} | IP != `` [$__auto])))"
    }
   ]
  }
 ]
}